In [7]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import statsmodels.api as sm

import json

In [19]:
with open('tournament_1.json','rb') as f:

    data = json.load(f)
print(data)

{'name': 'tournament_1', 'start_date': '2014-01-08', 'end_date': '2014-01-17', 'games': {'tour_1': [{'white': '贾叶珍', 'black': '范辰妮', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_1'}, {'white': '吕亚光', 'black': '李嘉爵', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_2'}, {'white': '刘奇喜', 'black': '刘晓鹏', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_3'}, {'white': '陆桂姐', 'black': '郑新聪', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_4'}, {'white': '李汶玲', 'black': '叶天英', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_5'}, {'white': '薛冠', 'black': '杨钰', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_6'}, {'white': '冯燕家', 'black': '曹灵缨', 'date': '2014-01-08', 'result': 0, 'id': 'tournament_1_7'}, {'white': '刘家坚', 'black': '齐慧智', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_8'}, {'white': '张志琼', 'black': '吴秋', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_9'}, {'white': '徐先广', 'black': '吴昱明', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_10'}, {'white': '杨佩义', 'black': '王由航', 'date': '2014-01-08', 'result': 0, 'id': 'tournament_1_11'}, {'white': '王永赟', 'black': '方东', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_12'}, {'white': '刘宇福', 'black': '朱有荣', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_13'}, {'white': '杨莎强', 'black': '余冬春', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_14'}, {'white': '孟芳全', 'black': '阎斯钧', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_15'}, {'white': '钟弘存', 'black': '张半植', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_16'}, {'white': '范存妞', 'black': '何建芝', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_17'}, {'white': '李琳华', 'black': '毛心磊', 'date': '2014-01-08', 'result': 0, 'id': 'tournament_1_18'}, {'white': '袁小昆', 'black': '董玉波', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_19'}, {'white': '李文子', 'black': '何驿艳', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_20'}, {'white': '刘先', 'black': '梁扬', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_21'}, {'white': '杨燕波', 'black': '袁宪萍', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_22'}, {'white': '陈思刚', 'black': '刘星梅', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_23'}, {'white': '张延营', 'black': '张燕', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_24'}, {'white': '张安甜', 'black': '张木兴', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_25'}, {'white': '李松江', 'black': '王千迅', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_26'}, {'white': '梁良', 'black': '殷小', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_27'}, {'white': '董海非', 'black': '魏兴', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_28'}, {'white': '毛均承', 'black': '彭国', 'date': '2014-01-08', 'result': 0.5, 'id': 'tournament_1_29'}, {'white': '李守超', 'black': '谢庆麟', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_30'}, {'white': '王剑铭', 'black': '陈音亮', 'date': '2014-01-08', 'result': 1, 'id': 'tournament_1_31'}, {'white': '杨承', 'black': '沈岚鸿', 'date': '2014-01-08', 'result': 0, 'id': 'tournament_1_32'}, {'white': '张家懿', 'black': '李巧芸', 'date': '2014-01-08', 'result': 0, 'id': 'tournament_1_33'}], 'tour_2': [{'white': '曹灵缨', 'black': '陆桂姐', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_34'}, {'white': '王由航', 'black': '刘家坚', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_35'}, {'white': '毛心磊', 'black': '张志琼', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_36'}, {'white': '沈岚鸿', 'black': '徐先广', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_37'}, {'white': '李巧芸', 'black': '刘宇福', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_38'}, {'white': '范辰妮', 'black': '范存妞', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_39'}, {'white': '李嘉爵', 'black': '李文子', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_40'}, {'white': '刘晓鹏', 'black': '刘先', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_41'}, {'white': '叶天英', 'black': '张延营', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_42'}, {'white': '杨钰', 'black': '张安甜', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_43'}, {'white': '方东', 'black': '李松江', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_44'}, {'white': '余冬春', 'black': '梁良', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_45'}, {'white': '阎斯钧', 'black': '李守超', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_46'}, {'white': '张半植', 'black': '王剑铭', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_47'}, {'white': '董玉波', 'black': '贾叶珍', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_48'}, {'white': '袁宪萍', 'black': '吕亚光', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_49'}, {'white': '刘星梅', 'black': '刘奇喜', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_50'}, {'white': '魏兴', 'black': '李汶玲', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_51'}, {'white': '彭国', 'black': '薛冠', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_52'}, {'white': '郑新聪', 'black': '王永赟', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_53'}, {'white': '齐慧智', 'black': '杨莎强', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_54'}, {'white': '吴秋', 'black': '孟芳全', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_55'}, {'white': '吴昱明', 'black': '钟弘存', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_56'}, {'white': '朱有荣', 'black': '袁小昆', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_57'}, {'white': '何建芝', 'black': '杨燕波', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_58'}, {'white': '何驿艳', 'black': '陈思刚', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_59'}, {'white': '梁扬', 'black': '董海非', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_60'}, {'white': '张燕', 'black': '毛均承', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_61'}, {'white': '张木兴', 'black': '冯燕家', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_62'}, {'white': '王千迅', 'black': '杨佩义', 'date': '2014-01-09', 'result': 0, 'id': 'tournament_1_63'}, {'white': '殷小', 'black': '李琳华', 'date': '2014-01-09', 'result': 0.5, 'id': 'tournament_1_64'}, {'white': '谢庆麟', 'black': '杨承', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_65'}, {'white': '陈音亮', 'black': '张家懿', 'date': '2014-01-09', 'result': 1, 'id': 'tournament_1_66'}], 'tour_3': [{'white': '刘家坚', 'black': '沈岚鸿', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_67'}, {'white': '范存妞', 'black': '曹灵缨', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_68'}, {'white': '李文子', 'black': '毛心磊', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_69'}, {'white': '张延营', 'black': '李巧芸', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_70'}, {'white': '李守超', 'black': '杨钰', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_71'}, {'white': '陆桂姐', 'black': '方东', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_72'}, {'white': '张志琼', 'black': '张半植', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_73'}, {'white': '刘宇福', 'black': '董玉波', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_74'}, {'white': '刘先', 'black': '刘星梅', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_75'}, {'white': '梁良', 'black': '彭国', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_76'}, {'white': '杨莎强', 'black': '王由航', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_77'}, {'white': '杨燕波', 'black': '刘晓鹏', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_78'}, {'white': '毛均承', 'black': '余冬春', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_79'}, {'white': '徐先广', 'black': '袁宪萍', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_80'}, {'white': '张安甜', 'black': '魏兴', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_81'}, {'white': '李松江', 'black': '吴秋', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_82'}, {'white': '王剑铭', 'black': '梁扬', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_83'}, {'white': '吕亚光', 'black': '张木兴', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_84'}, {'white': '李汶玲', 'black': '谢庆麟', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_85'}, {'white': '王永赟', 'black': '陈音亮', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_86'}, {'white': '钟弘存', 'black': '范辰妮', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_87'}, {'white': '袁小昆', 'black': '李嘉爵', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_88'}, {'white': '陈思刚', 'black': '叶天英', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_89'}, {'white': '杨佩义', 'black': '阎斯钧', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_90'}, {'white': '贾叶珍', 'black': '郑新聪', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_91'}, {'white': '刘奇喜', 'black': '吴昱明', 'date': '2014-01-10', 'result': 0.5, 'id': 'tournament_1_92'}, {'white': '薛冠', 'black': '朱有荣', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_93'}, {'white': '孟芳全', 'black': '何驿艳', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_94'}, {'white': '董海非', 'black': '殷小', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_95'}, {'white': '李琳华', 'black': '齐慧智', 'date': '2014-01-10', 'result': 1, 'id': 'tournament_1_96'}, {'white': '冯燕家', 'black': '何建芝', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_97'}, {'white': '杨承', 'black': '张燕', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_98'}, {'white': '张家懿', 'black': '王千迅', 'date': '2014-01-10', 'result': 0, 'id': 'tournament_1_99'}], 'tour_4': [{'white': '沈岚鸿', 'black': '李文子', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_100'}, {'white': '刘星梅', 'black': '张延营', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_101'}, {'white': '杨钰', 'black': '范存妞', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_102'}, {'white': '曹灵缨', 'black': '李守超', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_103'}, {'white': '刘晓鹏', 'black': '陆桂姐', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_104'}, {'white': '谢庆麟', 'black': '张志琼', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_105'}, {'white': '吴秋', 'black': '刘宇福', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_106'}, {'white': '毛心磊', 'black': '梁良', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_107'}, {'white': '李巧芸', 'black': '毛均承', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_108'}, {'white': '方东', 'black': '刘家坚', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_109'}, {'white': '张半植', 'black': '杨莎强', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_110'}, {'white': '董玉波', 'black': '徐先广', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_111'}, {'white': '彭国', 'black': '张安甜', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_112'}, {'white': '王由航', 'black': '王剑铭', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_113'}, {'white': '陈音亮', 'black': '吕亚光', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_114'}, {'white': '朱有荣', 'black': '钟弘存', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_115'}, {'white': '余冬春', 'black': '陈思刚', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_116'}, {'white': '袁宪萍', 'black': '刘先', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_117'}, {'white': '魏兴', 'black': '杨燕波', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_118'}, {'white': '梁扬', 'black': '王永赟', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_119'}, {'white': '张木兴', 'black': '袁小昆', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_120'}, {'white': '李嘉爵', 'black': '杨佩义', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_121'}, {'white': '阎斯钧', 'black': '贾叶珍', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_122'}, {'white': '吴昱明', 'black': '孟芳全', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_123'}, {'white': '何建芝', 'black': '董海非', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_124'}, {'white': '张燕', 'black': '李琳华', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_125'}, {'white': '范辰妮', 'black': '李松江', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_126'}, {'white': '王千迅', 'black': '李汶玲', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_127'}, {'white': '叶天英', 'black': '刘奇喜', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_128'}, {'white': '郑新聪', 'black': '薛冠', 'date': '2014-01-11', 'result': 0, 'id': 'tournament_1_129'}, {'white': '何驿艳', 'black': '冯燕家', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_130'}, {'white': '殷小', 'black': '张家懿', 'date': '2014-01-11', 'result': 0.5, 'id': 'tournament_1_131'}, {'white': '齐慧智', 'black': '杨承', 'date': '2014-01-11', 'result': 1, 'id': 'tournament_1_132'}], 'tour_5': [{'white': '范存妞', 'black': '沈岚鸿', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_133'}, {'white': '毛均承', 'black': '刘星梅', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_134'}, {'white': '李文子', 'black': '曹灵缨', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_135'}, {'white': '张延营', 'black': '刘晓鹏', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_136'}, {'white': '张志琼', 'black': '方东', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_137'}, {'white': '梁良', 'black': '吴秋', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_138'}, {'white': '徐先广', 'black': '谢庆麟', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_139'}, {'white': '吕亚光', 'black': '彭国', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_140'}, {'white': '李守超', 'black': '毛心磊', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_141'}, {'white': '陆桂姐', 'black': '杨钰', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_142'}, {'white': '刘宇福', 'black': '张半植', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_143'}, {'white': '杨莎强', 'black': '朱有荣', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_144'}, {'white': '王剑铭', 'black': '余冬春', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_145'}, {'white': '钟弘存', 'black': '王由航', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_146'}, {'white': '杨燕波', 'black': '张木兴', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_147'}, {'white': '刘家坚', 'black': '吴昱明', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_148'}, {'white': '张安甜', 'black': '王千迅', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_149'}, {'white': '陈思刚', 'black': '李巧芸', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_150'}, {'white': '刘先', 'black': '董玉波', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_151'}, {'white': '王永赟', 'black': '袁宪萍', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_152'}, {'white': '杨佩义', 'black': '陈音亮', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_153'}, {'white': '贾叶珍', 'black': '梁扬', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_154'}, {'white': '董海非', 'black': '李嘉爵', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_155'}, {'white': '李琳华', 'black': '阎斯钧', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_156'}, {'white': '袁小昆', 'black': '何建芝', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_157'}, {'white': '孟芳全', 'black': '张燕', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_158'}, {'white': '李松江', 'black': '叶天英', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_159'}, {'white': '薛冠', 'black': '何驿艳', 'date': '2014-01-12', 'result': 0, 'id': 'tournament_1_160'}, {'white': '李汶玲', 'black': '范辰妮', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_161'}, {'white': '刘奇喜', 'black': '魏兴', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_162'}, {'white': '冯燕家', 'black': '殷小', 'date': '2014-01-12', 'result': 1, 'id': 'tournament_1_163'}, {'white': '张家懿', 'black': '齐慧智', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_164'}, {'white': '杨承', 'black': '郑新聪', 'date': '2014-01-12', 'result': 0.5, 'id': 'tournament_1_165'}], 'tour_6': [{'white': '沈岚鸿', 'black': '毛均承', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_166'}, {'white': '刘星梅', 'black': '范存妞', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_167'}, {'white': '曹灵缨', 'black': '梁良', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_168'}, {'white': '刘晓鹏', 'black': '徐先广', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_169'}, {'white': '彭国', 'black': '张志琼', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_170'}, {'white': '吴秋', 'black': '吕亚光', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_171'}, {'white': '方东', 'black': '李守超', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_172'}, {'white': '张半植', 'black': '陆桂姐', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_173'}, {'white': '吴昱明', 'black': '杨莎强', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_174'}, {'white': '谢庆麟', 'black': '杨燕波', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_175'}, {'white': '王由航', 'black': '李文子', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_176'}, {'white': '余冬春', 'black': '张延营', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_177'}, {'white': '王千迅', 'black': '王剑铭', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_178'}, {'white': '李嘉爵', 'black': '钟弘存', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_179'}, {'white': '何建芝', 'black': '刘先', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_180'}, {'white': '何驿艳', 'black': '杨佩义', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_181'}, {'white': '杨钰', 'black': '刘宇福', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_182'}, {'white': '毛心磊', 'black': '张安甜', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_183'}, {'white': '朱有荣', 'black': '陈思刚', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_184'}, {'white': '张木兴', 'black': '王永赟', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_185'}, {'white': '李巧芸', 'black': '贾叶珍', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_186'}, {'white': '袁宪萍', 'black': '李琳华', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_187'}, {'white': '梁扬', 'black': '刘家坚', 'date': '2014-01-13', 'result': 0, 'id': 'tournament_1_188'}, {'white': '阎斯钧', 'black': '董海非', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_189'}, {'white': '叶天英', 'black': '孟芳全', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_190'}, {'white': '张燕', 'black': '李松江', 'date': '2014-01-13', 'result': 1, 'id': 'tournament_1_191'}, {'white': '董玉波', 'black': '李汶玲', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_192'}, {'white': '陈音亮', 'black': '袁小昆', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_193'}, {'white': '魏兴', 'black': '薛冠', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_194'}, {'white': '齐慧智', 'black': '刘奇喜', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_195'}, {'white': '范辰妮', 'black': '张家懿', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_196'}, {'white': '殷小', 'black': '杨承', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_197'}, {'white': '郑新聪', 'black': '冯燕家', 'date': '2014-01-13', 'result': 0.5, 'id': 'tournament_1_198'}], 'tour_7': [{'white': '梁良', 'black': '沈岚鸿', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_199'}, {'white': '范存妞', 'black': '刘晓鹏', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_200'}, {'white': '徐先广', 'black': '刘星梅', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_201'}, {'white': '毛均承', 'black': '曹灵缨', 'date': '2014-01-14', 'result': 1, 'id': 'tournament_1_202'}, {'white': '吕亚光', 'black': '张半植', 'date': '2014-01-14', 'result': 0, 'id': 'tournament_1_203'}, {'white': '李守超', 'black': '彭国', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_204'}, {'white': '张志琼', 'black': '吴昱明', 'date': '2014-01-14', 'result': 1, 'id': 'tournament_1_205'}, {'white': '陆桂姐', 'black': '谢庆麟', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_206'}, {'white': '杨莎强', 'black': '李嘉爵', 'date': '2014-01-14', 'result': 1, 'id': 'tournament_1_207'}, {'white': '李文子', 'black': '余冬春', 'date': '2014-01-14', 'result': 0.5, 'id': 'tournament_1_208'}, {'white': '刘先', 'black': '吴秋', 'date': '2014-01-14', 'result': 1, 'id': 

In [33]:
# Read the JSON file
data = pd.read_json('tournament_1.json')

# Write the CSV file
data.to_csv('output.csv', index=False)
data.head()

,name,start_date,end_date,games,tours,time_control
tour_1,tournament_1,2014-01-08,2014-01-17,"[{'white': '贾叶珍', 'black': '范辰妮', 'date': '201...",9,rapid
tour_2,tournament_1,2014-01-08,2014-01-17,"[{'white': '曹灵缨', 'black': '陆桂姐', 'date': '201...",9,rapid
tour_3,tournament_1,2014-01-08,2014-01-17,"[{'white': '刘家坚', 'black': '沈岚鸿', 'date': '201...",9,rapid
tour_4,tournament_1,2014-01-08,2014-01-17,"[{'white': '沈岚鸿', 'black': '李文子', 'date': '201...",9,rapid
tour_5,tournament_1,2014-01-08,2014-01-17,"[{'white': '范存妞', 'black': '沈岚鸿', 'date': '201...",9,rapid

In [ ]:
#merging mutilpe json files
# List of JSON files to merge
json_files = ['tournament_1.json','tournament_10.json','tournament_100.json','tournament_101','tournament_102.json']

# Read the JSON files into a list of DataFrames
dfs = [pd.read_json(file) for file in json_files]

# Concatenate the DataFrames into a single DataFrame
data = pd.concat(dfs, ignore_index=True)

# Write the DataFrame to a CSV file
data.to_csv('output.csv', index=False)

In [35]:
import pandas as pd
import json

json_files = ['tournament_1.json','tournament_10.json','tournament_100.json','tournament_101.json','tournament_102.json']
# Read the JSON files into a list of DataFrames
dfs = [pd.read_json(file) for file in json_files]

# Concatenate the DataFrames into a single DataFrame
data = pd.concat(dfs, ignore_index=True)

# Write the DataFrame to a CSV file
data.to_csv('output.csv', index=False)

# Extract the games data
games_data = []
for tour, games in data['games'].items():
    for game in games:
        game['tour'] = tour
        games_data.append(game)

# Convert the games data to a Pandas DataFrame
df = pd.DataFrame(games_data)

# Write the DataFrame to a CSV file
df.to_csv('tournament.csv', index=False)

In [25]:

df.shape

(1469, 6)

In [26]:
df.head()

  white black        date  result              id  tour
0   贾叶珍   范辰妮  2014-01-08     0.5  tournament_1_1     0
1   吕亚光   李嘉爵  2014-01-08     0.5  tournament_1_2     0
2   刘奇喜   刘晓鹏  2014-01-08     0.5  tournament_1_3     0
3   陆桂姐   郑新聪  2014-01-08     1.0  tournament_1_4     0
4   李汶玲   叶天英  2014-01-08     0.5  tournament_1_5     0

In [27]:
df.tail()

,white,black,date,result,id,tour
1464,"Li, Minkang","Hong, Xueyou",2014-09-04,0.0,tournament_102_148,52
1465,"Zhang, Zhengnan","Shi, Yufa",2014-09-04,0.5,tournament_102_149,52
1466,"Wu, Dongping","Zhang, Jia",2014-09-04,0.5,tournament_102_150,52
1467,"Qin, Huifei","Chen, Chunqian",2014-09-04,1.0,tournament_102_151,52
1468,"Lv, Yinwen","Chen, Si",2014-09-04,1.0,tournament_102_152,52

In [31]:
# ELO SCORES()

import pandas as pd

# Load the games data
games_data = pd.read_csv('tournament.csv')

# Initialize the Elo ratings for each player
elo_ratings = {}

# Set the initial Elo rating and the K-factor
initial_elo = 1200
k_factor = 32

# Iterate over each game
for index, row in games_data.iterrows():
    # Get the player IDs and the outcome of the game
    white = row['white']
    black = row['black']
    outcome = row['result']

    # Initialize the Elo ratings for the players if they don't exist
    if white not in elo_ratings:
        elo_ratings[white] = initial_elo
    if black not in elo_ratings:
        elo_ratings[black] = initial_elo

    # Calculate the expected scores
    rating1 = elo_ratings[white]
    rating2 = elo_ratings[black]
    expected_score1 = 1 / (1 + 10 ** ((rating2 - rating1) / 400))
    expected_score2 = 1 / (1 + 10 ** ((rating1 - rating2) / 400))

    # Calculate the actual scores
    if outcome == 'white won ':
        score1 = 1
        score2 = 0
    elif outcome == 'black won':
        score1 = 0
        score2 = 1
    else:
        score1 = 0.5
        score2 = 0.5

    # Update the Elo ratings
    elo_ratings[white] = rating1 + k_factor * (score1 - expected_score1)
    elo_ratings[black] = rating2 + k_factor * (score2 - expected_score2)

# Convert the Elo ratings to a Pandas DataFrame
elo_data = pd.DataFrame(list(elo_ratings.items()), columns=['white_player , black_player', 'elo_rating'])

# Write the Elo ratings to a CSV file
elo_data.to_csv('elo_ratings.csv', index=False)
print(elo_data)
elo_data.head()

    white_player , black_player  elo_rating
0                           贾叶珍      1200.0
1                           范辰妮      1200.0
2                           吕亚光      1200.0
3                           李嘉爵      1200.0
4                           刘奇喜      1200.0
..                          ...         ...
237              Zhang, Xiucong      1200.0
238                   Shi, Yufa      1200.0
239                   Xing, Xin      1200.0
240                   Yang, Yue      1200.0
241                  Lv, Yinwen      1200.0

[242 rows x 2 columns]

  white_player , black_player  elo_rating
0                         贾叶珍      1200.0
1                         范辰妮      1200.0
2                         吕亚光      1200.0
3                         李嘉爵      1200.0
4                         刘奇喜      1200.0

In [32]:
elo_data.tail()

    white_player , black_player  elo_rating
237              Zhang, Xiucong      1200.0
238                   Shi, Yufa      1200.0
239                   Xing, Xin      1200.0
240                   Yang, Yue      1200.0
241                  Lv, Yinwen      1200.0

In [36]:
import pandas as pd

# Step 1: Base URL for the JSON files
base_url = 'https://github.com/SunilGorantla/QT_Batch_0011/raw/main/Machine_Learning/datasets/chess/train'

# Step 2: List of JSON filenames to be read
file_names = [
    'tournament_1.json', 'tournament_1.json', 'tournament_10.json', 'tournament_10.json', 'tournament_100.json', 'tournament_100.json', 
    'tournament_101.json', 'tournament_101.json', 'tournament_102.json', 'tournament_102.json', 'tournament_103.json', 'tournament_103.json',
]

# Step 3: Initialize an empty list to store DataFrames
dfs = []

# Step 4: Loop through the file names, read each file, and append to the list
for file_name in file_names:
    file_url = f"{base_url}/{file_name}"
    try:
        df = pd.read_json(file_url)
        dfs.append(df)
    except Exception as e:
        print(f"Error reading {file_url}: {e}")

# Step 5: Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

# Step 6: Reset index to ensure unique index values
combined_df.reset_index(drop=True, inplace=True)

# Step 7: Check the structure of the DataFrame
print("Columns in the DataFrame:", combined_df.columns)
print("Sample data in the DataFrame:", combined_df.head())

# Step 8: Handle the 'games' column
if 'games' in combined_df.columns:
    # Ensure 'games' column contains lists
    if combined_df['games'].apply(lambda x: isinstance(x, list)).all():
        # Explode the 'games' column to separate rows for each game
        games_df = combined_df.explode('games')
        
        # Reset index after exploding
        games_df.reset_index(drop=True, inplace=True)
        
        # Convert the exploded 'games' column to a DataFrame
        games_details_df = pd.json_normalize(games_df['games'])

        # Concatenate the new games details DataFrame with the original DataFrame (excluding the old 'games' column)
        final_df = pd.concat([games_df.drop(columns='games'), games_details_df], axis=1)

        # Reset index again after concatenation
        final_df.reset_index(drop=True, inplace=True)

        # Display the new DataFrame structure
        print("Final DataFrame Structure:")
        print(final_df.head())

        # Optional: Save the new DataFrame to a CSV file for further analysis
        final_df.to_csv('simplified_chess_data.csv', index=False)
    else:
        print("The 'games' column does not contain lists.")
else:
    print("The 'games' column is missing.")

Columns in the DataFrame: Index(['name', 'start_date', 'end_date', 'games', 'tours', 'time_control'], dtype='object')
Sample data in the DataFrame:            name  start_date    end_date  \
0  tournament_1  2014-01-08  2014-01-17
1  tournament_1  2014-01-08  2014-01-17
2  tournament_1  2014-01-08  2014-01-17
3  tournament_1  2014-01-08  2014-01-17
4  tournament_1  2014-01-08  2014-01-17

                                               games  tours time_control
0  [{'white': '贾叶珍', 'black': '范辰妮', 'date': '201...      9        rapid
1  [{'white': '曹灵缨', 'black': '陆桂姐', 'date': '201...      9        rapid
2  [{'white': '刘家坚', 'black': '沈岚鸿', 'date': '201...      9        rapid
3  [{'white': '沈岚鸿', 'black': '李文子', 'date': '201...      9        rapid
4  [{'white': '范存妞', 'black': '沈岚鸿', 'date': '201...      9        rapid
Final DataFrame Structure:
           name  start_date    end_date  tours time_control white black  \
0  tournament_1  2014-01-08  2014-01-17      9        rapid   贾叶珍   范辰妮
1  tournament_1  2014-01-08  2014-01-17      9        rapid   吕亚光   李嘉爵
2  tournament_1  2014-01-08  2014-01-17      9        rapid   刘奇喜   刘晓鹏
3  tournament_1  2014-01-08  2014-01-17      9        rapid   陆桂姐   郑新聪
4  tournament_1  2014-01-08  2014-01-17      9        rapid   李汶玲   叶天英

         date  result              id
0  2014-01-08     0.5  tournament_1_1
1  2014-01-08     0.5  tournament_1_2
2  2014-01-08     0.5  tournament_1_3
3  2014-01-08     1.0  tournament_1_4
4  2014-01-08     0.5  tournament_1_5

In [38]:
final_df = final_df.drop_duplicates()
final_df

,name,start_date,end_date,tours,time_control,white,black,date,result,id
0,tournament_1,2014-01-08,2014-01-17,9,rapid,贾叶珍,范辰妮,2014-01-08,0.5,tournament_1_1
1,tournament_1,2014-01-08,2014-01-17,9,rapid,吕亚光,李嘉爵,2014-01-08,0.5,tournament_1_2
2,tournament_1,2014-01-08,2014-01-17,9,rapid,刘奇喜,刘晓鹏,2014-01-08,0.5,tournament_1_3
3,tournament_1,2014-01-08,2014-01-17,9,rapid,陆桂姐,郑新聪,2014-01-08,1.0,tournament_1_4
4,tournament_1,2014-01-08,2014-01-17,9,rapid,李汶玲,叶天英,2014-01-08,0.5,tournament_1_5
...,...,...,...,...,...,...,...,...,...,...
3257,tournament_103,2014-09-08,2014-09-08,12,classic,宋曼燊,杨俊瑞,2014-09-08,0.5,tournament_103_239
3258,tournament_103,2014-09-08,2014-09-08,12,classic,杨燕波,秦守云,2014-09-08,0.5,tournament_103_240
3259,tournament_103,2014-09-08,2014-09-08,12,classic,陈荣顺,张正男,2014-09-08,1.0,tournament_103_241
3260,tournament_103,2014-09-08,2014-09-08,12,classic,张跃,张雅娟,2014-09-08,0.0,tournament_103_242
3261,tournament_103,2014-09-08,2014-09-08,12,classic,宋萌妹,刘延兵,2014-09-08,1.0,tournament_103_243

In [39]:

final_df['series_no'] = final_df['id'].str.split('_', n=2).str[2]
final_df['Tournment_serial'] = final_df['name'].str.split('_', n=1).str[1]

final_df.head( )

,name,start_date,end_date,tours,time_control,white,black,date,result,id,series_no,Tournment_serial
0,tournament_1,2014-01-08,2014-01-17,9,rapid,贾叶珍,范辰妮,2014-01-08,0.5,tournament_1_1,1,1
1,tournament_1,2014-01-08,2014-01-17,9,rapid,吕亚光,李嘉爵,2014-01-08,0.5,tournament_1_2,2,1
2,tournament_1,2014-01-08,2014-01-17,9,rapid,刘奇喜,刘晓鹏,2014-01-08,0.5,tournament_1_3,3,1
3,tournament_1,2014-01-08,2014-01-17,9,rapid,陆桂姐,郑新聪,2014-01-08,1.0,tournament_1_4,4,1
4,tournament_1,2014-01-08,2014-01-17,9,rapid,李汶玲,叶天英,2014-01-08,0.5,tournament_1_5,5,1

In [40]:
final_df.head(10000 )

,name,start_date,end_date,tours,time_control,white,black,date,result,id,series_no,Tournment_serial
0,tournament_1,2014-01-08,2014-01-17,9,rapid,贾叶珍,范辰妮,2014-01-08,0.5,tournament_1_1,1,1
1,tournament_1,2014-01-08,2014-01-17,9,rapid,吕亚光,李嘉爵,2014-01-08,0.5,tournament_1_2,2,1
2,tournament_1,2014-01-08,2014-01-17,9,rapid,刘奇喜,刘晓鹏,2014-01-08,0.5,tournament_1_3,3,1
3,tournament_1,2014-01-08,2014-01-17,9,rapid,陆桂姐,郑新聪,2014-01-08,1.0,tournament_1_4,4,1
4,tournament_1,2014-01-08,2014-01-17,9,rapid,李汶玲,叶天英,2014-01-08,0.5,tournament_1_5,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...
3257,tournament_103,2014-09-08,2014-09-08,12,classic,宋曼燊,杨俊瑞,2014-09-08,0.5,tournament_103_239,239,103
3258,tournament_103,2014-09-08,2014-09-08,12,classic,杨燕波,秦守云,2014-09-08,0.5,tournament_103_240,240,103
3259,tournament_103,2014-09-08,2014-09-08,12,classic,陈荣顺,张正男,2014-09-08,1.0,tournament_103_241,241,103
3260,tournament_103,2014-09-08,2014-09-08,12,classic,张跃,张雅娟,2014-09-08,0.0,tournament_103_242,242,103
3261,tournament_103,2014-09-08,2014-09-08,12,classic,宋萌妹,刘延兵,2014-09-08,1.0,tournament_103_243,243,103

In [41]:
import pandas as pd

# Example initial ELO score
initial_elo = 1200

# Create a dictionary to store ELO ratings of players
elo_ratings = {}

# Function to calculate the expected score
def expected_score(elo_a, elo_b):
    return 1 / (1 + 10**((elo_b - elo_a) / 400))

# Function to update the ELO rating
def update_elo(elo, expected, actual, k=32):
    return elo + k * (actual - expected)

# Sort the DataFrame by 'Tournment_serial' and 'series_no'
final_df = final_df.sort_values(by=['Tournment_serial', 'series_no']).reset_index(drop=True)

# Initialize lists to store ELO scores for each match
white_elo_scores = []
black_elo_scores = []

# Iterate over each match in the DataFrame and update ELO scores
for _, row in final_df.iterrows():
    white_player = row['white']
    black_player = row['black']
    result = row['result']
    
    # Initialize ELO scores if players are not in the dictionary
    if white_player not in elo_ratings:
        elo_ratings[white_player] = initial_elo
    if black_player not in elo_ratings:
        elo_ratings[black_player] = initial_elo
    
    # Get current ELO ratings
    elo_white = elo_ratings[white_player]
    elo_black = elo_ratings[black_player]
    
    # Calculate expected scores
    expected_white = expected_score(elo_white, elo_black)
    expected_black = 1 - expected_white
    
    # Store current ELO scores
    white_elo_scores.append(elo_white)
    black_elo_scores.append(elo_black)
    
    # Determine actual scores based on match result
    if result == 1.0:  # White wins
        actual_white = 1.0
        actual_black = 0.0
    elif result == 0.0:  # Black wins
        actual_white = 0.0
        actual_black = 1.0
    else:  # Draw
        actual_white = 0.5
        actual_black = 0.5
    
    # Update ELO ratings
    elo_ratings[white_player] = update_elo(elo_white, expected_white, actual_white)
    elo_ratings[black_player] = update_elo(elo_black, expected_black, actual_black)

# Add the ELO scores to the DataFrame
final_df['white_ELO_scores'] = white_elo_scores
final_df['black_ELO_scores'] = black_elo_scores

# Display the updated DataFrame
print(final_df.head())

           name  start_date    end_date  tours time_control white black  \
0  tournament_1  2014-01-08  2014-01-17      9        rapid   贾叶珍   范辰妮
1  tournament_1  2014-01-08  2014-01-17      9        rapid   徐先广   吴昱明
2  tournament_1  2014-01-08  2014-01-17      9        rapid   沈岚鸿   李文子
3  tournament_1  2014-01-08  2014-01-17      9        rapid   刘星梅   张延营
4  tournament_1  2014-01-08  2014-01-17      9        rapid    杨钰   范存妞

         date  result                id series_no Tournment_serial  \
0  2014-01-08     0.5    tournament_1_1         1                1
1  2014-01-08     1.0   tournament_1_10        10                1
2  2014-01-11     1.0  tournament_1_100       100                1
3  2014-01-11     1.0  tournament_1_101       101                1
4  2014-01-11     0.0  tournament_1_102       102                1

   white_ELO_scores  black_ELO_scores
0            1200.0            1200.0
1            1200.0            1200.0
2            1200.0            1200.0
3            1200.0            1200.0
4            1200.0            1200.0

In [44]:
final_df.columns

Index(['name', 'start_date', 'end_date', 'tours', 'time_control', 'white',
       'black', 'date', 'result', 'id', 'series_no', 'Tournment_serial',
       'white_ELO_scores', 'black_ELO_scores'],
      dtype='object')

In [45]:
import pandas as pd

# Convert 'start_date' and 'end_date' columns to datetime if they are not already
final_df['start_date'] = pd.to_datetime(final_df['start_date'])
final_df['end_date'] = pd.to_datetime(final_df['end_date'])

# Calculate the difference in days and store it in a new column 'Duration'
final_df['Duration'] = (final_df['end_date'] - final_df['start_date']).dt.days

# Display the updated DataFrame
print(final_df.head())

           name start_date   end_date  tours time_control white black  \
0  tournament_1 2014-01-08 2014-01-17      9        rapid   贾叶珍   范辰妮
1  tournament_1 2014-01-08 2014-01-17      9        rapid   徐先广   吴昱明
2  tournament_1 2014-01-08 2014-01-17      9        rapid   沈岚鸿   李文子
3  tournament_1 2014-01-08 2014-01-17      9        rapid   刘星梅   张延营
4  tournament_1 2014-01-08 2014-01-17      9        rapid    杨钰   范存妞

         date  result                id series_no Tournment_serial  \
0  2014-01-08     0.5    tournament_1_1         1                1
1  2014-01-08     1.0   tournament_1_10        10                1
2  2014-01-11     1.0  tournament_1_100       100                1
3  2014-01-11     1.0  tournament_1_101       101                1
4  2014-01-11     0.0  tournament_1_102       102                1

   white_ELO_scores  black_ELO_scores  Duration
0            1200.0            1200.0         9
1            1200.0            1200.0         9
2            1200.0            1200.0         9
3            1200.0            1200.0         9
4            1200.0            1200.0         9

In [46]:
categorical1=final_df[['time_control', 'white', 'black']]
categorical1.head()

  time_control white black
0        rapid   贾叶珍   范辰妮
1        rapid   徐先广   吴昱明
2        rapid   沈岚鸿   李文子
3        rapid   刘星梅   张延营
4        rapid    杨钰   范存妞

In [47]:
LE=final_df[['time_control', 'white', 'black']]
from sklearn import preprocessing
label_enc = preprocessing.LabelEncoder()
LE=LE.apply(label_enc.fit_transform)
LE.head()

   time_control  white  black
0             1    259    245
1             1    173    146
2             1    215    184
3             1    134    161
4             1    200    244

In [48]:
Numerical_1=final_df[['series_no', 'Tournment_serial', 'result', 'white_ELO_scores', 'black_ELO_scores']]
Numerical_1.head()

  series_no Tournment_serial  result  white_ELO_scores  black_ELO_scores
0         1                1     0.5            1200.0            1200.0
1        10                1     1.0            1200.0            1200.0
2       100                1     1.0            1200.0            1200.0
3       101                1     1.0            1200.0            1200.0
4       102                1     0.0            1200.0            1200.0

In [49]:
Numerical_1=final_df[['series_no', 'Tournment_serial', 'result', 'white_ELO_scores', 'black_ELO_scores']]
combined = pd.concat([Numerical_1,LE], axis=1)
combined.head()

,series_no,Tournment_serial,result,white_ELO_scores,black_ELO_scores,time_control,white,black
0,1,1,0.5,1200.0,1200.0,1,259,245
1,10,1,1.0,1200.0,1200.0,1,173,146
2,100,1,1.0,1200.0,1200.0,1,215,184
3,101,1,1.0,1200.0,1200.0,1,134,161
4,102,1,0.0,1200.0,1200.0,1,200,244

In [50]:
combined.columns

Index(['series_no', 'Tournment_serial', 'result', 'white_ELO_scores',
       'black_ELO_scores', 'time_control', 'white', 'black'],
      dtype='object')

In [51]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Assume 'combined' is your DataFrame

# Define the feature set (X) and the target variable (Y)
X = combined[['Tournment_serial','series_no', 'time_control', 'white', 'black','white_ELO_scores', 'black_ELO_scores']]
Y = combined['result']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.6, random_state=123)

# Create a linear regression model
model = LinearRegression(fit_intercept=True)

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model with various metrics

# Mean Squared Error
mse = mean_squared_error(y_test, y_pred)

# Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)

# R-squared
r2 = r2_score(y_test, y_pred)

# Adjusted R-squared
n = X_test.shape[0]  # number of samples
p = X_test.shape[1]  # number of predictors
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print(f"\nMean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"R-squared: {r2}")
print(f"Adjusted R-squared: {adjusted_r2}")

# Regularization: Lasso Regression
lasso_model = Lasso(alpha=1.0)
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)
lasso_r2 = r2_score(y_test, lasso_pred)
print(f"\nLasso R-squared: {lasso_r2}")

# Regularization: Ridge Regression
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)
ridge_r2 = r2_score(y_test, ridge_pred)
print(f"\nRidge R-squared: {ridge_r2}")

Mean Squared Error (MSE): 0.12858704758803882
Mean Absolute Error (MAE): 0.28529536392229665
R-squared: 0.02925203283517608
Adjusted R-squared: 0.01968127822932564

Lasso R-squared: 0.028798031975277194

Ridge R-squared: 0.029282753092370162

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

# Assuming 'combined' is your DataFrame

# Define the feature set (X) and the target variable (Y)
X = combined[['Tournment_serial','series_no', 'time_control', 'white', 'black','white_ELO_scores', 'black_ELO_scores']]
Y = combined['mapped_result']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=123)

# Create a logistic regression model
log_model = LogisticRegression(max_iter=1000, random_state=123)

# Train the model
log_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = log_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Generate a classification report (includes precision, recall, F1-score, and support)
class_report = classification_report(y_test, y_pred)

# Calculate the ROC AUC score (if the problem is binary classification)
roc_auc = roc_auc_score(y_test, y_pred) if len(Y.unique()) == 2 else 'N/A'  # ROC AUC is only for binary classification

# Display the results
print(f"Accuracy: {accuracy}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

if roc_auc != 'N/A':
    print(f"ROC AUC Score: {roc_auc}")

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score
from scipy.stats import randint, uniform

# Assuming 'combined' is your DataFrame

# Define the feature set (X) and the target variable (Y)
X = combined[['Tournment_serial','series_no', 'time_control', 'white', 'black','white_ELO_scores', 'black_ELO_scores']]
Y = combined['mapped_result']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.7, random_state=123)

# Create a Random Forest model
rf_model = RandomForestClassifier(random_state=123)

# Define a smaller grid of hyperparameters to search
param_dist = {
    'n_estimators': randint(100, 300),  # Number of trees in the forest
    'criterion': ['gini', 'entropy'],  # Function to measure quality of split
    'max_depth': [None, 10, 20, 30],   # Maximum depth of the tree
    'min_samples_split': randint(2, 10),  # Minimum number of samples required to split a node
    'min_samples_leaf': randint(1, 5),    # Minimum number of samples required at a leaf node
    'max_features': ['auto', 'sqrt'],  # Number of features to consider for the best split
    'bootstrap': [True, False]  # Whether bootstrap samples are used when building trees
}

# Set up Randomized Search with cross-validation
random_search = RandomizedSearchCV(estimator=rf_model, param_distributions=param_dist, n_iter=50, cv=3, n_jobs=-1, verbose=2, random_state=123)

# Train the model using Randomized Search
random_search.fit(X_train, y_train)

# Get the best model from Randomized Search
best_rf_model = random_search.best_estimator_

# Make predictions on the test set
y_pred = best_rf_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Generate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Generate a classification report (includes precision, recall, F1-score, and support)
class_report = classification_report(y_test, y_pred)

# Calculate the ROC AUC score (if the problem is binary classification)
roc_auc = roc_auc_score(y_test, best_rf_model.predict_proba(X_test)[:, 1]) if len(Y.unique()) == 2 else 'N/A'

# Display the results
print(f"Best Parameters: {random_search.best_params_}")
print(f"Accuracy: {accuracy}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

if roc_auc != 'N/A':
    print(f"ROC AUC Score: {roc_auc}")

NameError: name 'combined' is not defined

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt

# Generate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Plot confusion matrix
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=['0', '1', '2'], yticklabels=['0', '1', '2'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

NameError: name 'y_test' is not defined